name: Run React Tests

on: [push]  # This workflow will trigger on every push event

jobs:
  test:
    runs-on: ubuntu-latest  # The runner environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # This action checks out your repository's code
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # You can specify the Node.js version you want to use
      
      - name: Install dependencies
        run: npm install
      
      - name: Run tests
        run: npm test